### PR TITLE
Pale Moon 27.1+ support

### PR DESCRIPTION
**Pull request by JustOff**
Based on [PMkit documentation draft v1.1](https://github.com/JustOff/pm27-sdk-addons/blob/master/PMkit.md), tested with [Pale Moon 27.1.0b1](http://www.palemoon.org/unstable/).

### CODE REVIEW

**Comment by klemens** [comment]
Does this mean that palemoon users can install the same extension as firefox users or does the xpi have to be modified? I saw you changed the id, renamed `package.json` to `fackage.json`, modified `bootstrap.js` and added a `chrome.manifest`.

I can't test this right now, as my current gcc doesn't want to compile palemoon (and I don't want to install gcc5), but you seem to be sure that it works, so I will probably merge it anyway.

**Comment by JustOff** [comment]
All the changes I made before with id, manifest, and package.json were only the workaround for Pale Moon 27.0, because it has no official support for SDK-based add-ons. Now Pale Moon 27.1 is coming (currently beta) where SDK support returns via PMkit. So this PR will allow Pale Moon users to run your add-on from the same xpi as Firefox users.

**Comment by klemens** [comment]
Thanks for the link to the binaries. It seems to work fine after some quick testing, so here we go: 6005451ed56485244cc157e5fd0fac8a0081490f

Thank you for your effort!

**Comment by JustOff** [comment]
Thank you for supporting Pale Moon!

**Comment by klemens** [comment]
The new version is online (and on amo): https://github.com/klemens/ff-youtube-all-html5/releases/tag/v3.1.1

**Pull request closed without merging**
